"""Fix user password default

Revision ID: 46c189b33bc3
Revises: e46ab1874b5b
Create Date: 2025-01-21 22:39:02.343475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c189b33bc3'
down_revision = 'e46ab1874b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_clothing_items')
    with op.batch_alter_table('clothing_items', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('outfit_items', schema=None) as batch_op:
        batch_op.alter_column('outfit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('clothing_item_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('outfits', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outfits', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('outfit_items', schema=None) as batch_op:
        batch_op.alter_column('clothing_item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('outfit_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('clothing_items', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('_alembic_tmp_clothing_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('category', sa.VARCHAR(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('color', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_clothing_items_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
